---
title: "Articulo Scopus FRN"
author: "Juan Fernado Renón"
date: "18 de septiembre de 2017"
output: html_document
---


Las oeraciones de intermediación financiera exponen a las entidades que las ejecutan  al Riesgo de Liquidez, el cual  se define como la contingencia de no poder cumplir de manera plena y oportuna con las obligaciones de pago en las fechas correspondientes debido a la insuficiencia de recursos líquidos o a la necesidad de asumir costos inusuales de fondeo.  

La materialización del riesgo de liquidez genera requerimientos  de recursos líquidos, que pueden  cubrirse a través de la liquidación de sus activos. La liquidación de dichos activos de manera contingente, puede  generar perdidas al si se hace a precios inferiores de los esperados. Esta situación  puede generar contagio en el sistema finananciero, a través del efecto que dicha contingencia pueda tener sobre la liquidez del mercado y la percepción del público sobre la estabilidad y la viabilidad del sistema financiero.


Con el fin de evitar la materialización del riesgo de liquidez, se requiere un sistema de administración de dicho riesgo, que permita a los intermediarios financieros:  identificar, medir, controlar y monitorear este riesgo.


Un sistema de administración de riesgo de liquidez, debe de incorporar la proyección de los flujos de ingresos y egresos que tendran las entidades para un horizonte de tiempo dado.

Según el anexo 1 del capítulo 6 de la circular basica contable y fincnaicera emitida por la Superintendencia Financiera de COlombia (SFC), el cual proporciona la metodología para la implelentación de un Sistema de Administración de Riesgo de Liquidez estándar, los flujos de ingresos y egresos de las entidades financieras  se pueden clasificar como flujos con vencimientos contractuales y no cntractuales. La diferencia fundamental de estos flujos, es que los los flujos con vencimientos contractuales se presentan en  fechas y montos  prestablecidos , mientras  que para  los flujos que presentan vencimientos no contractuales,  se desconocen las fechas y los montos.



Para la proyección de los flujos con vencimietos no contractuales, la SFC propone la estimación del Factor de Retiro Neto (FRN), el cual es un parámetro que se obtiene de los valores de la cola de la distribución de retiros originados por posiciones que no tienen vencimientos prestablecidos.



En este trabajo  se propone una metodología basa en modelos de series de tiempo ARIMA y GARCH para hacer la estimación de los retiros netos de caja originados en posiciones de rubros que no tienen vencimientos prestablecidos en entidades financieras de Colombia para el periodo 2003-2016 a través de la modelación de la serie de tiempo de los retiros mensuales del sistema financiero Colombiano. 

La metodología propuesta se compara a través de preubas de hipotesis estadisticas  con la metodología propuesta por la SFC para la medición estándar del riesgo de liquidez

